"""add vocabulary

Revision ID: 09640b8a10bb
Revises: f5487f792d2c
Create Date: 2025-05-03 22:08:38.145389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09640b8a10bb'
down_revision: Union[str, None] = 'f5487f792d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('english_word', sa.String(length=200), nullable=False),
    sa.Column('russian_translation', sa.String(length=200), nullable=False),
    sa.Column('is_learned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('learned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'english_word', 'russian_translation', name='unique_user_word')
    )
    op.create_index(op.f('ix_user_vocabulary_id'), 'user_vocabulary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vocabulary_id'), table_name='user_vocabulary')
    op.drop_table('user_vocabulary')
    # ### end Alembic commands ###
