"""Edit media, add new tables

Revision ID: 1767abee30ef
Revises: 60e3db86d91c
Create Date: 2025-03-19 13:46:10.038139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1767abee30ef'
down_revision: Union[str, None] = '60e3db86d91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_id'), 'subtitles', ['id'], unique=False)
    op.add_column('media', sa.Column('episode_id', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('quality', sa.String(length=50), nullable=True))
    op.drop_constraint('media_series_id_fkey', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'episodes', ['episode_id'], ['id'])
    op.drop_column('media', 'type')
    op.drop_column('media', 'series_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_series_id_fkey', 'media', 'series', ['series_id'], ['id'])
    op.drop_column('media', 'quality')
    op.drop_column('media', 'episode_id')
    op.drop_index(op.f('ix_subtitles_id'), table_name='subtitles')
    op.drop_table('subtitles')
    # ### end Alembic commands ###
