"""add metrics

Revision ID: 2c54f85d313f
Revises: 95ab83aac9c2
Create Date: 2025-05-03 23:09:00.185771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c54f85d313f'
down_revision: Union[str, None] = '95ab83aac9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_popularity_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_metrics_type_period', 'content_popularity_metrics', ['content_type', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_content_popularity_metrics_id'), 'content_popularity_metrics', ['id'], unique=False)
    op.add_column('movies', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('series', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'is_featured')
    op.drop_column('movies', 'is_featured')
    op.drop_index(op.f('ix_content_popularity_metrics_id'), table_name='content_popularity_metrics')
    op.drop_index('ix_content_metrics_type_period', table_name='content_popularity_metrics')
    op.drop_table('content_popularity_metrics')
    # ### end Alembic commands ###
