"""edit tables

Revision ID: 458d3222d6be
Revises: f775942fb71e
Create Date: 2025-05-04 01:55:35.960514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458d3222d6be'
down_revision: Union[str, None] = 'f775942fb71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('eng_name', sa.String(length=255), nullable=True))
    op.add_column('actors', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('actors', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('actors', 'birth_date')
    op.add_column('countries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('countries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('episodes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('episodes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('genres', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('genres', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('media', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('media', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('movies', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('movies', 'created_at',
               existing_type=sa.DATE(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('seasons', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('seasons', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('series', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('series', 'created_at',
               existing_type=sa.DATE(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('subtitles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('subtitles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtitles', 'updated_at')
    op.drop_column('subtitles', 'created_at')
    op.alter_column('series', 'created_at',
               existing_type=sa.DateTime(),
               server_default=None,
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('series', 'updated_at')
    op.drop_column('seasons', 'updated_at')
    op.drop_column('seasons', 'created_at')
    op.alter_column('movies', 'created_at',
               existing_type=sa.DateTime(),
               server_default=None,
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('movies', 'updated_at')
    op.drop_column('media', 'updated_at')
    op.drop_column('media', 'created_at')
    op.drop_column('genres', 'updated_at')
    op.drop_column('genres', 'created_at')
    op.drop_column('episodes', 'updated_at')
    op.drop_column('episodes', 'created_at')
    op.drop_column('countries', 'updated_at')
    op.drop_column('countries', 'created_at')
    op.add_column('actors', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('actors', 'updated_at')
    op.drop_column('actors', 'created_at')
    op.drop_column('actors', 'eng_name')
    # ### end Alembic commands ###
