"""Edit movies/series tables

Revision ID: 5ebe83a0c140
Revises: 417997f1d6fb
Create Date: 2025-03-12 21:31:20.462567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebe83a0c140'
down_revision: Union[str, None] = '417997f1d6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('movies', 'release_date')
    op.drop_column('seasons', 'release_date')
    op.add_column('series', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('series', 'release_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('series', 'description')
    op.drop_column('series', 'year')
    op.add_column('seasons', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'description')
    op.drop_column('movies', 'year')
    # ### end Alembic commands ###
