"""Fix subscription column (is_active)

Revision ID: 9a60b7d40487
Revises: ae05d5c3b26d
Create Date: 2025-03-12 19:24:27.555822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a60b7d40487'
down_revision: Union[str, None] = 'ae05d5c3b26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('is_active', sa.Boolean(), nullable=False, server_default="true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'is_active')
    # ### end Alembic commands ###
