"""Edit movies, series tables

Revision ID: 9e3274692f03
Revises: 8320186b489d
Create Date: 2025-03-19 14:01:42.197295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3274692f03'
down_revision: Union[str, None] = '8320186b489d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('cover_url', sa.String(length=500), nullable=True))
    op.add_column('movies', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('series', sa.Column('cover_url', sa.String(length=500), nullable=True))
    op.add_column('series', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'thumbnail_url')
    op.drop_column('series', 'cover_url')
    op.drop_column('movies', 'thumbnail_url')
    op.drop_column('movies', 'cover_url')
    # ### end Alembic commands ###
