"""Edit movies, series table/ Add diffoculty

Revision ID: 9ee3984142f8
Revises: fd5beacd83ff
Create Date: 2025-03-26 17:29:27.535230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee3984142f8'
down_revision: Union[str, None] = 'fd5beacd83ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('series', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('series', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'series', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series', type_='unique')
    op.drop_column('series', 'slug')
    op.drop_column('series', 'difficulty')
    op.drop_column('movies', 'difficulty')
    # ### end Alembic commands ###
