"""Fix subscription

Revision ID: ae05d5c3b26d
Revises: 5cfdfcda93d6
Create Date: 2025-03-12 19:05:54.520268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae05d5c3b26d'
down_revision: Union[str, None] = '5cfdfcda93d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_at', sa.Date(), nullable=False))
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'created_at')
    # ### end Alembic commands ###
