"""edit stats

Revision ID: e91e556d0ef5
Revises: c1861f8b2de3
Create Date: 2025-05-03 00:58:24.666760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91e556d0ef5'
down_revision: Union[str, None] = 'c1861f8b2de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', 'content_type', name='unique_user_content_like')
    )
    op.create_index(op.f('ix_user_likes_id'), 'user_likes', ['id'], unique=False)
    op.drop_index('ix_statistics_id', table_name='statistics')
    op.drop_table('statistics')
    op.drop_index('ix_likes_id', table_name='likes')
    op.drop_table('likes')
    op.add_column('movies', sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('movies', sa.Column('likes_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('series', sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('series', sa.Column('likes_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'likes_count')
    op.drop_column('series', 'views_count')
    op.drop_column('movies', 'likes_count')
    op.drop_column('movies', 'views_count')
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='likes_movie_id_fkey'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='likes_series_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='likes_pkey')
    )
    op.create_index('ix_likes_id', 'likes', ['id'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='statistics_movie_id_fkey'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='statistics_series_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='statistics_pkey')
    )
    op.create_index('ix_statistics_id', 'statistics', ['id'], unique=False)
    op.drop_index(op.f('ix_user_likes_id'), table_name='user_likes')
    op.drop_table('user_likes')
    # ### end Alembic commands ###
